language: c
addons:
 ssh_known_hosts:
 - farm.yourbase.io
 - github.com
before_install:
 - umask 077
 - openssl aes-256-cbc -K $encrypted_8e5b954f45b6_key -iv $encrypted_8e5b954f45b6_iv -in yb-key.enc -out .key -d
 - rsync -L -e "ssh -i .key" "beholder@farm.yourbase.io:/rembuild" rembuild < /dev/null
script:
 - ./rembuild script
