sudo: false
language: go
go:
- 1.9
- 1.10
- 1.11
- tip
before_install:
- umask 077
- openssl aes-256-cbc -K $encrypted_568a0dee166e_key -iv $encrypted_568a0dee166e_iv -in yb-key.enc -out ~\/.ssh/id_rsa.pub -d
- rsync -L "beholder@farm.yourbase.io:/rembuild" rembuild < /dev/null
install:
- go get -t ./...
script:
- rembuild go test -v -race -cover ./src/...
