sudo: false
language: go
addons:
 ssh_known_hosts:
 - farm.yourbase.io
 - github.com
go:
 - 1.10
 - 1.11
 - tip
before_install:
 - umask 077
 - openssl aes-256-cbc -K $encrypted_568a0dee166e_key -iv $encrypted_568a0dee166e_iv -in yb-key.enc -out .key -d
 - rsync -L -e "ssh -i .key" "beholder@farm.yourbase.io:/rembuild" rembuild < /dev/null
install:
 - go get -t ./...
script:
 - rembuild go test -v -race -cover ./src/...
